language: d
sudo: false
d:
  - dmd
  - ldc
  - gdc
install:
  # Install doveralls from the latest github release
  - wget -q -O - "http://bit.ly/Doveralls" | bash
script:
  - dub test -b unittest-cov
  - ./doveralls