language: d
sudo: false
d:
  - dmd
  - dmd-beta
  - ldc
  - gdc
matrix:
  allow_failures:
    - d: dmd-beta
    - d: ldc
    - d: gdc
install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.1/doveralls_linux_travis"
  - chmod +x doveralls
script:
  - dub test -b unittest-cov
  - dub build -b ddox
  - ./doveralls
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master