language: d
sudo: false
d:
  - dmd
  - dmd-beta
  - ldc
  - gdc
matrix:
  allow_failures:
    - d: dmd-beta
    - d: ldc
    - d: gdc
script:
  - dub test -b unittest-cov
  - dub fetch doveralls
  - dub run doveralls
before_deploy:
  - dub build -b ddox
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  on:
    tags: true