// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'natcmp', kind: "module", path: './natcmp.html', attributes: []},
{name: 'natcmp.compareNatural', kind: "functiondeclaration", path: './natcmp/compareNatural.html', attributes: []},
{name: 'natcmp.compareNaturalSort', kind: "functiondeclaration", path: './natcmp/compareNaturalSort.html', attributes: []},
{name: 'natcmp.comparePathsNatural', kind: "functiondeclaration", path: './natcmp/comparePathsNatural.html', attributes: []},
{name: 'natcmp.comparePathsNaturalSort', kind: "functiondeclaration", path: './natcmp/comparePathsNaturalSort.html', attributes: []},
{name: 'natcmp.NaturalComparable', kind: "templatedeclaration", path: './natcmp/NaturalComparable.html', attributes: []},
{name: 'natcmp.NaturalPathComparable', kind: "templatedeclaration", path: './natcmp/NaturalPathComparable.html', attributes: []},
];
